version: '3'

services:
  nextjs:
    image: sukibrown/contract-manager-fe-nextjs:latest
    container_name: contract_manager_fe
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - nginx-proxy
    labels:
      - "project=contract-manager-fe"
      - "service=nextjs"

networks:
  nginx-proxy:
    external: true
